// Generated by https://quicktype.io

export interface TvShowListRatedResponse {
    page: number;
    results: Result[];
    total_pages: number;
    total_results: number;
}

export interface Result {
    adult: boolean;
    backdrop_path: string;
    genre_ids: number[];
    id: number;
    origin_country: OriginCountry[];
    original_language: OriginalLanguage;
    original_name: string;
    overview: string;
    popularity: number;
    poster_path: string;
    first_air_date: string;
    name: string;
    vote_average: number;
    vote_count: number;
    rating: number;
}

export enum OriginCountry {
    Us = "US",
}

export enum OriginalLanguage {
    En = "en",
}